core/urls.py
from django.urls import path,include
from core.views import index,payment,dashboard,order_detail, product_list_view,invoice_view, category_list_view,category_product_list_view,vendor_list_view,vendor_detail_view,product_detail_view,tag_list,ajax_add_review,search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,update_cart,checkout_view,payment_failed_view,payment_completed_view,add_to_wishlist,wishlist_view,remove_wishlist
# from bkash.bkash import Bkash

app_name = "core"

urlpatterns = [
    #homepage
    path("", index, name='index'),
  
    path("products/", product_list_view, name = "product-list"),
    path("product/<pid>/", product_detail_view, name = "product-detail"),
    
    #Category
    path("category/", category_list_view, name = "category-list"),
    path("category/<cid>/", category_product_list_view, name = "category-product-list"),
    #Vendor
    
    path("vendors/", vendor_list_view, name = "vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name = "vendor-detail"),

    #tags
    path("product/tag/<slug:tag_slug>/", tag_list, name = "tags"),

    #add reviews
    path("ajax-add-review/<int:pid>/", ajax_add_review, name = "ajax-add-review"),
    #search
    path("search/", search_view, name = "search"),

    #filter
    path("filter-product/", filter_product, name = "filter-product"),

    #add to cart
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    #cart page
    path("cart/", cart_view, name = "cart"),

    #delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),

    #update cart
    path("update-cart/", update_cart, name = "update-cart"),

    #checkout URL
    path("checkout/", checkout_view, name = "checkout"),
    #invoice URL
    path('invoice/', payment_completed_view,name='invoice' ),

    #path Paypal
    path('paypal/', include("paypal.standard.ipn.urls")),
    
    path("payment/<int:oid>", payment,name='payment'),
    #Bkash

    # path('bkash/', include('bkash.urls')),
    # path('bkash/', include('bkash.urls')),


    # url(r'^bKash_payment/', include('bKash_payment.urls')),


    #payment successful
    path('payment-completed/',payment_completed_view, name = "payment-completed" ),
    

    #failed
    path('payment-failed/',payment_failed_view, name = "payment-failed" ),


    #wishlist page
    path('wishlist/',wishlist_view, name = "wishlist" ),


    #Add_t0_wishlist
    path('add-to-wishlist/',add_to_wishlist, name = "add-to-wishlist" ),

    #del wishlist
    path('remove-from-wishlist/',remove_wishlist, name = "remove-from-wishlist" ),

    # dashboard
    path("dashboard/",dashboard,name='dashboard' ),
    path("dashboard/order/<int:id>",order_detail,name='order-detail')
    
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")), #
    path("user/", include("userauths.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")),



    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"write review "}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from sslcommerz_lib import SSLCOMMERZ 
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from core.models import Product, Category, Vendor, ProductImages,CartOrderItems, CartOrder,ProductReview, wishlist_model, Address
from userauths.models import User
from taggit.models import Tag
from django.db.models import Count,Avg
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.core import serializers


def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status = "published" ).order_by('-date')
    for product in products:
        print(product)
    
    categories = Category.objects.all()
    context = {
        "products" : products,
        "categories":categories

    }
    return render(request, 'core/index.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status = "published" )
    print(products)
    context = {
        "products" : products
    }
    return render(request, 'core/product-list.html', context)




def payment(request,oid):
    settings = { 'store_id': 'testbox', 'store_pass': 'qwerty', 'issandbox': True }
    print(request.POST.keys())
    sslcommez = SSLCOMMERZ(settings)
    order = CartOrder.objects.get(id=oid)
    host = request.get_host()
    post_body = {}
    post_body['total_amount'] = order.price
    post_body['currency'] = "BDT"
    post_body['tran_id'] = order.id
    post_body['success_url'] = 'http://{}{}'.format(host,reverse("core:invoice")),
    post_body['fail_url'] = "your fail url"
    post_body['cancel_url'] = "your cancel url"
    post_body['emi_option'] = 0
    post_body['cus_name'] = request.user
    post_body['cus_email'] = request.user.email
    post_body['cus_phone'] = "01700000000"
    post_body['cus_add1'] = "customer address"
    post_body['cus_city'] = "Dhaka"
    post_body['cus_country'] = "Bangladesh"
    post_body['shipping_method'] = "NO"
    post_body['multi_card_name'] = ""
    post_body['num_of_item'] = 1
    post_body['product_name'] = "Test"
    post_body['product_category'] = "Test Category"
    post_body['product_profile'] = "general"


    response = sslcommez.createSession(post_body)
    
    return HttpResponseRedirect(response['GatewayPageURL'],)
# Create your views here.
def category_list_view(request):

    categories = Category.objects.all()
    #categories = Category.objects.annotate(product_count=Count('product')).order_by('-product_count')[:5]

    context = {
        "categories": categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(product_status="published", category = category)

    context = {
        "category": category,
        "products": products,

    }
    return render(request, 'core/category-product-list.html', context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,

    }
    return render(request, 'core/vendor-list.html', context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid = vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    #weight_options = ["50g", "60g", "80g", "100g", "150g"]
    context = {
        "vendor": vendor,
        "products": products,
        


    }
    return render(request, 'core/vendor-detail.html', context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid = pid)
    p_image = product.p_images.all()
    products = Product.objects.filter(category = product.category).exclude(pid=pid)


    ###################
    weight_options = ["50g", "80g", "100g", "150g","200g","500g","1000g"]

    ###############
    reviews = ProductReview.objects.filter(product= product).order_by("-date")
    #getting avg reviews
    average_rating = ProductReview.objects.filter(product= product).aggregate(rating=Avg('rating'))


    # Calculate the count of each rating
    rating_counts = reviews.values('rating').annotate(count=Count('rating')).order_by('rating')

    # Initialize dictionary to hold star counts
    star_counts = {i: 0 for i in range(1, 6)}

    # Fill the star_counts dictionary with actual counts
    for item in rating_counts:
        star_counts[item['rating']] = item['count']

    # Calculate total number of reviews
    total_reviews = reviews.count()

    # Calculate percentage for each star rating
    star_percentages = {star: (count / total_reviews) * 100 if total_reviews > 0 else 0 for star, count in star_counts.items()}

    # Calculate average rating percentage
    average_rating_percentage = (average_rating['rating'] / 5) * 100 if average_rating['rating'] else 0

    #Product review form
    review_form = ProductReviewForm()


    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False




    context = {
        "p": product,
        "p_image": p_image,
        "weight_options": weight_options,
        "current_weight": product.weight,
        "reviews": reviews,
        "products": products,
        "average_rating": average_rating,
        'average_rating_percentage': average_rating_percentage,
        'star_percentages': star_percentages,
        'review_form':review_form,
        'make_review':make_review,






    }
    return render(request, 'core/product-detail.html', context)


def tag_list(request,tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag,

    }
    return render(request, 'core/tag.html', context)   

def  ajax_add_review(request,pid):
    #try:

    product = Product.objects.get(id=pid)
    # except Product.DoesNotExist:
    #     return JsonResponse({'error': 'Product not found'}, status=404)
    user = request.user


    review = ProductReview.objects.create(

        user = user,
        product = product,
        review = request.POST["review"],
        rating = request.POST["rating"],
    )

    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],

    }

    avg_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
            'bool':True,
            "context": context,
            'avg_reviews': avg_reviews,
        }
    )

def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
        

    }
    return render(request, 'core/search.html', context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status = "published" ).order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

     
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()  

    context = {
        "products": products,
    }

    data = render_to_string("core/async/product-list.html", context)
    return JsonResponse({"data": data})


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        "title" : request.GET['title'],
        "qty" : request.GET['qty'],
        "price" : request.GET['price'],
        "image" : request.GET['image'],
        "pid" : request.GET['pid'],

    }
    
    if "cart_data_obj" in request.session:
        if str(request.GET["id"]) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]["qty"] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data

        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data


    else:

        request.session['cart_data_obj'] = cart_product

    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})



def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id ,item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])


        return render(request, 'core/cart.html',{"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
     
    else:
         
        messages.warning(request, "Your cart is empty")
        #  return render(request, 'core/cart.html',{"cart_data": '', 'totalcartitems': len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
        return redirect("core:index")
    

templates/core/checkout.html
{% extends 'partials/base.html'  %}
{% load static %}
{% block content %}



    <!--End header-->
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href='index.html' rel='nofollow'><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{totalcartitems}}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row mb-50">
                        <div class="col-lg-6 mb-sm-15 mb-lg-0 mb-md-3">
                            {%  if request.user.is_authenticated %}

                            {%else %}
                            <div class="toggle_info">
                                <span><i class="fi-rs-user mr-10"></i><span class="text-muted font-lg">Already have an account?</span> <a href="#loginform" data-bs-toggle="collapse" class="collapsed font-lg" aria-expanded="false">Click here to login</a></span>
                            </div>
                            {%endif%}
                            <div class="panel-collapse collapse login_form" id="loginform">
                                <div class="panel-body">
                                    <p class="mb-30 font-sm">If you have shopped with us before, please enter your details below. If you are a new customer, please proceed to the Billing &amp; Shipping section.</p>
                                    <form method="post">
                                        <div class="form-group">
                                            <input type="text" name="email" placeholder="Username Or Email">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" placeholder="Password">
                                        </div>
                                        <div class="login_footer form-group">
                                            <div class="chek-form">
                                                <div class="custome-checkbox">
                                                    <input class="form-check-input" type="checkbox" name="checkbox" id="remember" value="">
                                                    <label class="form-check-label" for="remember"><span>Remember me</span></label>
                                                </div>
                                            </div>
                                            <a href="#">Forgot password?</a>
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-md" name="login">Log in</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <form method="post" class="apply-coupon">
                                <input type="text" placeholder="Enter Coupon Code...">
                                <button class="btn  btn-md" name="login">Apply Coupon</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <h4 class="mb-30">Billing Details</h4>
                        <form method="post">
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" required name="fname" placeholder="Name *" value="{{request.user}}">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input type="text" required name="mobile" placeholder="Mobile *" value={{address.mobile}}>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" name="address" required placeholder="Address *" value="{{address.address}}">
                                </div>
                            </div>
                           
                        </form>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border p-40 cart-totals ml-30 mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Your Order</h4>
                            <h6 class="text-muted">Subtotal</h6>
                        </div>
                        <div class="divider-2 mb-30"></div>
                        <div class="table-responsive order_table checkout">
                            <table class="table no-border">
                                <tbody>
                                    {% for p_id,item in cart_data.items %}
                                    <tr>
                                        <td class="image product-thumbnail"><img src=" {{item.image}} " alt="#"></td>
                                        <td>
                                            <h6 class="w-160 mb-5"><a class='text-heading' href='shop-product-full.html'>{{item.title | title}}</a></h6></span>
                                            <div class="product-rate-cover">
                                                <div class="product-rate d-inline-block">
                                                    <div class="product-rating" style="width:90%">
                                                    </div>
                                                </div>
                                                <span class="font-small ml-5 text-muted"> (4.0)</span>
                                            </div>
                                        </td>
                                        <td>
                                            <h6 class="text-muted pl-20 pr-20">x {{item.qty}}</h6>
                                        </td>
                                        <td>
                                            <h4 class="text-brand">{{item.price}}</h4>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="payment ml-30">
                        <h4 class="mb-30">Payment</h4>
                        <div class="payment_option">
                           
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" value="online" id="exampleRadios5" checked="">
                                <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                            </div>
                            
                        </div>
                       
                        <a href="{% url 'core:payment' order.id%}" class="btn btn-fill-out btn-block mt-30">Place an Order<i class="fi-rs-sign-out ml-15"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </main>
 
    {% endblock content %}

templates/core/order-detail.html
{% extends 'partials/base.html'  %}
{% load static %}
{% block content %}

<table class="table table-striped invoice-table mt-25">
    <thead class="bg-active">
        <tr>
            <th>Item</th>
            <th class="text-center">Unit Price</th>
            <th class="text-center">Quantity</th>
            <th class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for item in  orderItems %}
        <tr>
            <td>
                <div class="item-desc-1">
                    <span>{{item.item}}</span>

                </div>
            </td>
            <td class="text-center">{{item.price}}</td>
            <td class="text-center">{{item.qty}}</td>
            <td class="text-right"> {{item.total}} </td>
        </tr>
      {% endfor %}
        <tr>
            <td colspan="3" class="text-end f-w-600">SubTotal</td>
            <td class="text-right"> {{order.price}} </td>
        </tr>
       
        <tr>
            <td colspan="3" class="text-end f-w-600">Grand Total</td>
            <td class="text-right f-w-600">{{order.price}}</td>
        </tr>
    </tbody>
</table>
{% endblock%}

templates/core/vendor-list.html
{% extends 'partials/base.html'  %}
{% load static %}
{% block content %}

    <main class="main pages mb-80">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href='index.html' rel='nofollow'><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Vendors List
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="archive-header-2 text-center">
                    <h1 class="display-2 mb-50">Vendors List</h1>
                    <div class="row">
                        <div class="col-lg-5 mx-auto">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Search vendors (by name or ID)..." />
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-50">
                    <div class="col-12 col-lg-8 mx-auto">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p>We have <strong class="text-brand">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now!!</p>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Mall</a></li>
                                            <li><a href="#">Featured</a></li>
                                            <li><a href="#">Preferred</a></li>
                                            <li><a href="#">Total items</a></li>
                                            <li><a href="#">Avg. Rating</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row vendor-grid">
                    {% for v in vendors %}
                    <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            <div class="product-badges product-badges-position product-badges-mrg">
                                <!-- <span class="hot">Mall</span> -->
                            </div>
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="{% url 'core:vendor-detail' v.vid %}">
                                        <img class="default-img" src="{{v.image.url}}"  style="height: 140px; width: 140px;"  alt="" />
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">{{v.product.all.count}} Product{{v.product.all.count|pluralize}}</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since {{v.date|date:"Y"}}</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'core:vendor-detail' v.vid %}">{{v.title}}</a></h4>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>{{v.address}}</span></li>
                                            <li><img src="assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>{{v.contact}}</span></li>
                                        </ul>
                                        
                                    </div>
                                    <br>
                                    <a class='btn btn-xs' href="{% url 'core:vendor-detail' v.vid %}">Visit Store <i class="fi-rs-arrow-small-right"></i></a>

                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                </div>
                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">6</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}


    