core/urls.py
from django.urls import path,include
from core.views import index,payment,dashboard,order_detail, product_list_view,invoice_view, category_list_view,category_product_list_view,vendor_list_view,vendor_detail_view,product_detail_view,tag_list,ajax_add_review,search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,update_cart,checkout_view,payment_failed_view,payment_completed_view,add_to_wishlist,wishlist_view,remove_wishlist
# from bkash.bkash import Bkash

app_name = "core"

urlpatterns = [
    #homepage
    path("", index, name='index'),
  
    path("products/", product_list_view, name = "product-list"),
    path("product/<pid>/", product_detail_view, name = "product-detail"),
    
    #Category
    path("category/", category_list_view, name = "category-list"),
    path("category/<cid>/", category_product_list_view, name = "category-product-list"),
    #Vendor
    
    path("vendors/", vendor_list_view, name = "vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name = "vendor-detail"),

    #tags
    path("product/tag/<slug:tag_slug>/", tag_list, name = "tags"),

    #add reviews
    path("ajax-add-review/<int:pid>/", ajax_add_review, name = "ajax-add-review"),
    #search
    path("search/", search_view, name = "search"),

    #filter
    path("filter-product/", filter_product, name = "filter-product"),

    #add to cart
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    #cart page
    path("cart/", cart_view, name = "cart"),

    #delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),

    #update cart
    path("update-cart/", update_cart, name = "update-cart"),

    #checkout URL
    path("checkout/", checkout_view, name = "checkout"),
    #invoice URL
    path('invoice/', payment_completed_view,name='invoice' ),

    #path Paypal
    path('paypal/', include("paypal.standard.ipn.urls")),
    
    path("payment/<int:oid>", payment,name='payment'),
    #Bkash

    # path('bkash/', include('bkash.urls')),
    # path('bkash/', include('bkash.urls')),


    # url(r'^bKash_payment/', include('bKash_payment.urls')),


    #payment successful
    path('payment-completed/',payment_completed_view, name = "payment-completed" ),
    

    #failed
    path('payment-failed/',payment_failed_view, name = "payment-failed" ),


    #wishlist page
    path('wishlist/',wishlist_view, name = "wishlist" ),


    #Add_t0_wishlist
    path('add-to-wishlist/',add_to_wishlist, name = "add-to-wishlist" ),

    #del wishlist
    path('remove-from-wishlist/',remove_wishlist, name = "remove-from-wishlist" ),

    # dashboard
    path("dashboard/",dashboard,name='dashboard' ),
    path("dashboard/order/<int:id>",order_detail,name='order-detail')
    
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")), #
    path("user/", include("userauths.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")),



    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"write review "}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from sslcommerz_lib import SSLCOMMERZ 
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from core.models import Product, Category, Vendor, ProductImages,CartOrderItems, CartOrder,ProductReview, wishlist_model, Address
from userauths.models import User
from taggit.models import Tag
from django.db.models import Count,Avg
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.core import serializers


def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status = "published" ).order_by('-date')
    for product in products:
        print(product)
    
    categories = Category.objects.all()
    context = {
        "products" : products,
        "categories":categories

    }
    return render(request, 'core/index.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status = "published" )
    print(products)
    context = {
        "products" : products
    }
    return render(request, 'core/product-list.html', context)




def payment(request,oid):
    settings = { 'store_id': 'testbox', 'store_pass': 'qwerty', 'issandbox': True }
    print(request.POST.keys())
    sslcommez = SSLCOMMERZ(settings)
    order = CartOrder.objects.get(id=oid)
    host = request.get_host()
    post_body = {}
    post_body['total_amount'] = order.price
    post_body['currency'] = "BDT"
    post_body['tran_id'] = order.id
    post_body['success_url'] = 'http://{}{}'.format(host,reverse("core:invoice")),
    post_body['fail_url'] = "your fail url"
    post_body['cancel_url'] = "your cancel url"
    post_body['emi_option'] = 0
    post_body['cus_name'] = request.user
    post_body['cus_email'] = request.user.email
    post_body['cus_phone'] = "01700000000"
    post_body['cus_add1'] = "customer address"
    post_body['cus_city'] = "Dhaka"
    post_body['cus_country'] = "Bangladesh"
    post_body['shipping_method'] = "NO"
    post_body['multi_card_name'] = ""
    post_body['num_of_item'] = 1
    post_body['product_name'] = "Test"
    post_body['product_category'] = "Test Category"
    post_body['product_profile'] = "general"


    response = sslcommez.createSession(post_body)
    
    return HttpResponseRedirect(response['GatewayPageURL'],)
# Create your views here.
def category_list_view(request):

    categories = Category.objects.all()
    #categories = Category.objects.annotate(product_count=Count('product')).order_by('-product_count')[:5]

    context = {
        "categories": categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(product_status="published", category = category)

    context = {
        "category": category,
        "products": products,

    }
    return render(request, 'core/category-product-list.html', context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,

    }
    return render(request, 'core/vendor-list.html', context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid = vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    #weight_options = ["50g", "60g", "80g", "100g", "150g"]
    context = {
        "vendor": vendor,
        "products": products,
        


    }
    return render(request, 'core/vendor-detail.html', context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid = pid)
    p_image = product.p_images.all()
    products = Product.objects.filter(category = product.category).exclude(pid=pid)


    ###################
    weight_options = ["50g", "80g", "100g", "150g","200g","500g","1000g"]

    ###############
    reviews = ProductReview.objects.filter(product= product).order_by("-date")
    #getting avg reviews
    average_rating = ProductReview.objects.filter(product= product).aggregate(rating=Avg('rating'))


    # Calculate the count of each rating
    rating_counts = reviews.values('rating').annotate(count=Count('rating')).order_by('rating')

    # Initialize dictionary to hold star counts
    star_counts = {i: 0 for i in range(1, 6)}

    # Fill the star_counts dictionary with actual counts
    for item in rating_counts:
        star_counts[item['rating']] = item['count']

    # Calculate total number of reviews
    total_reviews = reviews.count()

    # Calculate percentage for each star rating
    star_percentages = {star: (count / total_reviews) * 100 if total_reviews > 0 else 0 for star, count in star_counts.items()}

    # Calculate average rating percentage
    average_rating_percentage = (average_rating['rating'] / 5) * 100 if average_rating['rating'] else 0

    #Product review form
    review_form = ProductReviewForm()


    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False




    context = {
        "p": product,
        "p_image": p_image,
        "weight_options": weight_options,
        "current_weight": product.weight,
        "reviews": reviews,
        "products": products,
        "average_rating": average_rating,
        'average_rating_percentage': average_rating_percentage,
        'star_percentages': star_percentages,
        'review_form':review_form,
        'make_review':make_review,






    }
    return render(request, 'core/product-detail.html', context)


def tag_list(request,tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag,

    }
    return render(request, 'core/tag.html', context)   

def  ajax_add_review(request,pid):
    #try:

    product = Product.objects.get(id=pid)
    # except Product.DoesNotExist:
    #     return JsonResponse({'error': 'Product not found'}, status=404)
    user = request.user


    review = ProductReview.objects.create(

        user = user,
        product = product,
        review = request.POST["review"],
        rating = request.POST["rating"],
    )

    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],

    }

    avg_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
            'bool':True,
            "context": context,
            'avg_reviews': avg_reviews,
        }
    )

def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
        

    }
    return render(request, 'core/search.html', context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status = "published" ).order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

     
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()  

    context = {
        "products": products,
    }

    data = render_to_string("core/async/product-list.html", context)
    return JsonResponse({"data": data})


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        "title" : request.GET['title'],
        "qty" : request.GET['qty'],
        "price" : request.GET['price'],
        "image" : request.GET['image'],
        "pid" : request.GET['pid'],

    }
    
    if "cart_data_obj" in request.session:
        if str(request.GET["id"]) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]["qty"] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data

        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data


    else:

        request.session['cart_data_obj'] = cart_product

    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})



def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id ,item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])


        return render(request, 'core/cart.html',{"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
     
    else:
         
        messages.warning(request, "Your cart is empty")
        #  return render(request, 'core/cart.html',{"cart_data": '', 'totalcartitems': len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
        return redirect("core:index")
    

templates/core/async/product-list.html
{% for p in products %}
    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
        <div class="product-cart-wrap mb-30">
            <div class="product-img-action-wrap">
                <div class="product-img product-img-zoom">
                    <a href="{% url 'core:product-detail' p.pid %}">
                        <img class="default-img" src="{{ p.image.url }}" alt="" />
                        <img class="hover-img" src="{{ p.image.url }}" alt="" />
                    </a>
                </div>
                <div class="product-action-1">
                    <a aria-label='Add To Wishlist' class='action-btn' href='shop-wishlist.html'><i class="fi-rs-heart"></i></a>
                    <a aria-label='Compare' class='action-btn' href='shop-compare.html'><i class="fi-rs-shuffle"></i></a>
                    <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                </div>
                <div class="product-badges product-badges-position product-badges-mrg">
                    <span class="hot">-{{ p.get_percentage|floatformat:0 }}%</span>
                </div>
            </div>
            <div class="product-content-wrap">
                <div class="product-category">
                    <a href="{% url 'core:product-detail' p.pid %}">{{ p.category.title }}</a>
                </div>
                <h2><a href="{% url 'core:product-detail' p.pid %}">{{ p.title }}</a></h2>
                <div class="product-rate-cover">
                    <div class="product-rate d-inline-block">
                        <div class="product-rating" style="width: 90%"></div>
                    </div>
                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                </div>
                <div>
                    <span class="font-small text-muted">By <a href="{% url 'core:vendor-detail' p.vendor.vid %}">{{ p.vendor.title }}</a></span>
                </div>
                <div class="product-card-bottom">
                    <div class="product-price">
                        <span>৳{{ p.price }}</span>
                        <span class="old-price">৳{{ p.old_price }}</span>
                    </div>
                    <div class="add-cart">
                        <a class='add' href='shop-cart.html'><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/core/async/wishlist-list.html
    <!--End header-->
    <main class="main" >
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href='index.html' rel='nofollow'><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">{{wishlist.count}}</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                    {% for w in w %} 
                                    <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ w.product.image.url }}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class='product-name mb-10' href="{% url 'core:product-detail' w.product.pid %}">{{w.product.title|truncatechars:25}}</a></h6>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width: 90%"></div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                    </td>
                                    <td class="price d-fdlex fs-1" data-title="Price">
                                        <span class="text-brand">৳</span><span class="text-brand current-product-price-{{w.product.id}}">{{ w.product.price }}</snap>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}</span>
                                    </td>
                                    <td class="text-right" data-title="Cart">

                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ w.product.id  }}"  >
                                        <input type="hidden" value="{{w.product.pid}}"  class="product-pid-{{ w.product.id  }}"  >
                                        <input type="hidden" value="{{w.product.image.url}}"  class="product-image-{{ w.product.id  }}"  >
                                        <input type="hidden" value="{{w.product.title}}"  class="product-title-{{ w.product.id  }}"  >
                                        <input type="hidden" value="{{w.product.id}}"  class="product-id-{{ w.product.id  }}"  >
                                        <button class="btn btn-sm add-to-cart-btn" data-index="{{w.product.id}}">Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <!-- <a href="#" class="text-body"><i class="fi-rs-trash"></i></a> -->
                                        <button  style="border: none; background: none ;" data-wishlist-product="{{ w.id }}"   href="#" class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>

                                    </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="7" style="text-align: center; color: #ff0000; font-size: 20px; font-weight: bold;">
                                            Nothing in Wishlist Yet..
                                        </td>
                                    </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>